name: fpis
on:
  pull_request:
    branches:
      - master
  push:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Formatting test
        run: sbt scalafmtCheckAll